version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/username
      POSTGRES_PASSWORD_FILE: /run/secrets/password
    secrets:
      - username
      - password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

secrets:
  username:
    file: ./secrets/username.txt
  password:
    file: ./secrets/password.txt
